# .github/workflows/code-review.yml
name: Code Review
on: pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ollama
        uses: ai-action/setup-ollama@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Ask lama to translate'
        uses: ai-action/ollama-action@v2
        id: explanation
        with:
          model: tinyllama
          prompt: "What's a large language model?"
